name: Databricks artifacts publisher
on:
  workflow_dispatch:
env:
  ARTIFACT_BUCKET: immuta-platform-artiacts
  IMMUTA_RELEASE: 2024.2.0
  RELEASE_DATE: 20240430
  GH_TOKEN: ${{ github.token }}
permissions:
  id-token: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::931788537711:role/github-actions
    - name: Download files from s3
      run: |
        gh release create --repo ${{ github.repository }} ${{ env.IMMUTA_RELEASE }} --notes ""
        mkdir -p 11.x 7.x_8.x_9.x_10.x
        set -x
        for file in allowedCallingClasses.json get_unity_token.py immuta-benchmark-suite.dbc immuta-validation.py immuta_cluster_init_script.sh immuta_cluster_init_script_proxy.sh obscuredCommands.yaml; do
        #aws s3 cp s3://${{ env.ARTIFACT_BUCKET }}/hadoop/databricks/${{ env.IMMUTA_RELEASE }}/7.x_8.x_9.x_10.x/$file 7.x_8.x_9.x_10.x/;
          aws s3 cp s3://${{ env.ARTIFACT_BUCKET }}/hadoop/databricks/${{ env.IMMUTA_RELEASE }}/11.x/$file 11.x/;
          #gh release upload --repo ${{ github.repository }} ${{ env.IMMUTA_RELEASE }} "7.x_8.x_9.x_10.x/$file#7.x_8.x_9.x_10.x/$file";
          gh release upload --repo ${{ github.repository }} ${{ env.IMMUTA_RELEASE }} "11.x/$file#11.x/$file";
        done
        #aws s3 cp s3://${{ env.ARTIFACT_BUCKET }}/hadoop/databricks/${{ env.IMMUTA_RELEASE }}/7.x_8.x_9.x_10.x/immuta-spark-hive-${{ env.IMMUTA_RELEASE}}_${{ env.RELEASE_DATE }}-spark-3.1.1-public.jar 7.x_8.x_9.x_10.x/
        aws s3 cp s3://${{ env.ARTIFACT_BUCKET }}/hadoop/databricks/${{ env.IMMUTA_RELEASE }}/11.x/immuta-spark-hive-${{ env.IMMUTA_RELEASE}}_${{ env.RELEASE_DATE }}-spark-3.3.1-public.jar 11.x/
        #gh release upload --repo ${{ github.repository }} ${{ env.IMMUTA_RELEASE }} "7.x_8.x_9.x_10.x/immuta-spark-hive-${{ env.IMMUTA_RELEASE}}_${{ env.RELEASE_DATE }}-spark-3.1.1-public.jar#7.x_8.x_9.x_10.x/immuta-spark-hive-${{ env.IMMUTA_RELEASE }}_${{ env.RELEASE_DATE }}-spark-3.1.1-public.jar";
        gh release upload --repo ${{ github.repository }} ${{ env.IMMUTA_RELEASE }} "11.x/immuta-spark-hive-${{ env.IMMUTA_RELEASE }}_${{ env.RELEASE_DATE }}-spark-3.3.0-public.jar#11.x/immuta-spark-hive-${{ env.IMMUTA_RELEASE }}_${{ env.RELEASE_DATE }}-spark-3.3.0-public.jar";
